import type { Metadata } from "next";
import "./globals.css";
import { Poetsen_One } from 'next/font/google'
import NextAuthsessionProvider from "@/providers/sessionProvider";

const mainFontFamaly = Poetsen_One({
  weight: ['400'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={mainFontFamaly.className}>
        <NextAuthsessionProvider>{children}</NextAuthsessionProvider>
      </body>
    </html>
  );
}
